# editorconfig: true
singleQuote: true
semi: true
useTabs: false
printWidth: 100
trailingComma: es5
endOfLine: lf
arrowParens: avoid
bracketSpacing: true
bracketSameLine: true
htmlWhitespaceSensitivity: ignore
plugins:
  - prettier-plugin-svelte
overrides:
  - files: '*.svelte'
    options:
      parser: svelte
